Setup code coverage

diff --git a/coverage b/coverage
--- a/coverage
+++ b/coverage
@@ -10,5 +10,19 @@ rm -fR cover/
 coverage erase
 # Discover and run all tests
 coverage run --concurrency=multiprocessing ./scripts/run_tests.py discover -v
+
 coverage combine
-coverage report
+res_combine=$?
+if [ $res_combine -ne 0 ]
+then
+  echo -e "Travis Build FAILURE: Coverage combine failed"
+  exit 1
+fi
+
+coverage report --fail-under=100
+coverage_report=$?
+if [ $coverage_report -ne 0 ]
+then
+  echo -e "Travis Build FAILURE: Coverage percentage failed"
+  exit 1
+fi
